### ISSUE TITLE
Fix key for `get_client(...)` caching

### ISSUE THREAD

**Issue by HaFl** [Yelp/swagger-py#96]
The client caching seems to be effectively disabled due to the changes introduced in 46a68a433bf106f7f3af113907d2305938bc0243. More specifically, I think that the problem manifests itself in line 65:
```
key = repr(args) + repr(kwargs)
```
For example, when `get_client(...)` gets called with the kwarg `http_client=AsynchronousHttpClient()`, then the return value of `repr(kwargs)` will include the specific memory address of the AsynchronousHttpClient object:
'http_client': \<swaggerpy.async_http_client.AsynchronousHttpClient object at **0x397ed10**\>

Therefore, actually a **unique key** is stored in the cache dict for every `get_client(...)` function call.

**Comment by dnephin** [comment]
oops, yes that sounds right

**Comment by dnephin** [comment]
I think using `repr()` is still correct here, the problem is that `AsynchronousHttpClient` does not have a `repr` that properly reflects it's state. Since `AsynchronousHttpClient` is actually stateless, every repr for an instance should be the same.

**Comment by bwbaugh** [comment]
@dnephin Isn't `kwargs` a `dict`? This might be moot, but since the order of a `dict` is undefined, it may not be "safe" to simply `repr` it, even though in practice the order is consistent.

As an anecdote, I believe golang actually randomizes the iteration order for their hash maps to force developers not to rely on the order. Though I understand that's Go and this is Python.

**Comment by dnephin** [comment]
Fair point, I guess this needs to be `kwargs.items()` as well.

I think in general this is probably not the best way to handle this problem.  Instead of having `swagger-py` cache the client, the application should hold a reference for as long as it makes sense.  I would argue that there is really no good reason to re-generate the client.  Any change to the API would require other code changes on the client, so re-fetching the api docs doesn't really do anything for you.

Instead of fixing this, maybe we should just remove the caching entirely.

**Comment by bwbaugh** [comment]
PS: I think `kwargs.items()` is also going to have an undefined order. Something more like `sorted(kwargs.items())` might work.

**Comment by dnephin** [comment]
There is some discussion about removing the caching in #87 as well

**Comment by HaFl** [comment]
In case we decide to keep `repr()` with a proper `__repr__()` method of `AsynchronousHttpClient`, then I'd definitely argue for adding a test since for new args / kwargs in the future we might run into the same issue again.

Interesting discussion in #87 and spontaneously I don't see too much of a need for caching the client aside from the swaggerpy response validation (seems to be more of a long term solution though).

**Comment by dnephin** [comment]
It's going to be difficult to test for every possibly param. Someone could easily use a different http client that also has a bad repr. Ultimately doing the caching in the application is the best way to handle this, because the application knows when it makes sense to re-use a client, and when it does not.

From this library we can only guess based on parameters, which is difficult.

**Comment by bwbaugh** [comment]
Perhaps there's a way we could design the API of `get_client` to allow an easier time of producing a cache key? Maybe expose a `cache_key` kwarg that the caller can provide?

If we end up making a backwards incompatible change to remove the client caching system within the package, it might be nice to provide an example in the docs for how the user could implement caching on their own.

----

From a user of the library perspective, one reason (whether it good or bad) that I would be an advocate of keeping the client cache logic within this package is that it makes it so I don't have to reintroduce the same caching logic in every repo where I use swagger-py / bravado.

I think it fundamentally comes down to whether or not refreshing the client is needed. If not, then it should be relatively simple for the user to create a module global. If it turns out there is good reason to refresh the client for a long lived program, then it can be painful to repeatedly implement the same check-refresh logic in each of the user's repos.

**Comment by dnephin** [comment]
Another option for the caching is to only cache the api-docs themselves instead of the whole client. That's much safer because it varies only by url/path instead of every arg/kwarg.  I had considered doing that at the time, but it would have been a much larger change, so I skipped it for now.

I'm still hoping we can remove the cache entirely.
